name: Create pnpm
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: next
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "9.5.0"
    - name: pnpm install
      run: |
        pnpm install
    - name: Archive Release source
      shell: bash
      run: |
        "/c/Program Files/7-Zip/7z.exe" a -m0=lzma2 -mx t0.7z "." -xr!/*node_modules/* -xr!.github -xr!*.mp4 -xr!*.mov -xr!*.gif
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          t0.7z
        tag_name: ${{ github.event.inputs.tags }}
